# Generated by Django 4.1.5 on 2023-01-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_product_comment_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ord_UV',
            new_name='ord_uv',
        ),
    ]
